name: vsim 
base: core18 
version: '0.9.0'
summary: Vsim is digital circuits simulator written in java
description: |
  Vsim is digital circuits simulator written in java.

grade: devel
confinement: devmode

apps:
  vsim:
    command: bin/start.sh
    plugs: [home, x11]
parts:
  vsim:
    after: [glib-only]
    plugin: dump
    source: .
    organize:
      'build/libs/vsim.jar': bin/
      'start.sh': bin/
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-8-jdk
  glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
